//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPSM_email.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class HPSM_Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HPSM_Settings defaultInstance = ((HPSM_Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HPSM_Settings())));
        
        public static HPSM_Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\SBT-Dmitriev-MV\\DEV\\Projects\\GetDataFromHPSM_email\\tmp_test")]
        public string pathToFiles {
            get {
                return ((string)(this["pathToFiles"]));
            }
            set {
                this["pathToFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("111")]
        public string prevFileName {
            get {
                return ((string)(this["prevFileName"]));
            }
            set {
                this["prevFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2016-02-10")]
        public global::System.DateTime prevFileCreatedDate {
            get {
                return ((global::System.DateTime)(this["prevFileCreatedDate"]));
            }
            set {
                this["prevFileCreatedDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HPSM_labor_*")]
        public string fileMask {
            get {
                return ((string)(this["fileMask"]));
            }
            set {
                this["fileMask"] = value;
            }
        }
    }
}
