//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALL_ZNI_BUGS_JIRA
    {
        public long ID { get; set; }
        public string ISSUE { get; set; }
        public string PROJECT { get; set; }
        public string COMPONENT { get; set; }
        public string REPORTER { get; set; }
        public string ASSIGNEE { get; set; }
        public string CREATOR { get; set; }
        public string ISSUETYPE { get; set; }
        public string SUMMARY { get; set; }
        public string DESCRIPTION { get; set; }
        public string ENVIRONMENT { get; set; }
        public string PRIORITY { get; set; }
        public string RESOLUTION { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
        public Nullable<System.DateTime> DUEDATE { get; set; }
        public Nullable<System.DateTime> RESOLUTIONDATE { get; set; }
    }
}
