//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONF_REP_LABOR_JIRA_HPSM
    {
        public string СИСТЕМА { get; set; }
        public string ПОДРАЗДНИЗ { get; set; }
        public string ПОДРАЗДВЕРХ { get; set; }
        public string Категория { get; set; }
        public string PROJECT { get; set; }
        public string КОДЗНИ { get; set; }
        public string НОМЕР_ЗНИ { get; set; }
        public Nullable<System.DateTime> ДАТА_РЕГ { get; set; }
        public string СТАТУСЗНИ { get; set; }
        public Nullable<System.DateTime> ДАТАРЕЗОЛЗНИ { get; set; }
        public string КОДЗАДАЧИ { get; set; }
        public string ТИПЗАПРОСА { get; set; }
        public string СТАТУСЗАДАЧИ { get; set; }
        public string ИСПОЛНИТЕЛЬ { get; set; }
        public Nullable<System.DateTime> ДАТАСОЗДАНИЯ { get; set; }
        public Nullable<System.DateTime> ДАТАРЕЗОЛЗАДАЧИ { get; set; }
        public Nullable<System.DateTime> ДАТА_РАБОТЫ { get; set; }
        public string АС_НОМЕР { get; set; }
        public string АС_НАЗВАНИЕ { get; set; }
        public Nullable<decimal> СУМТРУД { get; set; }
        public string ПОЛНОЕ_ИМЯ { get; set; }
        public Nullable<decimal> GRADE { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<decimal> ТРУДОЗАТРАТЫ { get; set; }
        public string WORK_TYPE_VAL { get; set; }
        public string ACCOUNT_VAL { get; set; }
        public decimal ID { get; set; }
        public string ПРИОРИТЕТ { get; set; }
    }
}
