//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_1C
    {
        public int ID { get; set; }
        public string ID_VACANCY { get; set; }
        public string PERSONNEL_NUMBER { get; set; }
        public string FIO { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string SECOND_NAME { get; set; }
        public string SAP { get; set; }
        public string SIGN { get; set; }
        public string CUSTOMER { get; set; }
        public Nullable<decimal> COUNT { get; set; }
        public string BLOCK { get; set; }
        public string CATEGORY { get; set; }
        public string OFFICE_SBT { get; set; }
        public string DEPARTMENT_SBT { get; set; }
        public Nullable<decimal> GRADE { get; set; }
        public string CHIEF { get; set; }
        public string OFFICE_CORP { get; set; }
        public string DEPARTMENT_CORP { get; set; }
        public string ORG_POSITION { get; set; }
        public string EMAIL { get; set; }
        public string CORP_POSITION { get; set; }
        public string FIO_PREV { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
    }
}
