//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HPSMLABOR
    {
        public int ID { get; set; }
        public string I_NUMBER { get; set; }
        public System.DateTime DT { get; set; }
        public decimal TIME_SPEND { get; set; }
        public string FIO { get; set; }
        public string KE { get; set; }
        public string OPERATOR { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
    }
}
