//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALL_ZNI_BUGS_JIRA> ALL_ZNI_BUGS_JIRA { get; set; }
        public virtual DbSet<CONF_REP_LABOR_JIRA_HPSM> CONF_REP_LABOR_JIRA_HPSM { get; set; }
        public virtual DbSet<DATA_1C> DATA_1C { get; set; }
        public virtual DbSet<HPSMLABOR> HPSMLABOR { get; set; }
        public virtual DbSet<TEMPOLABOR> TEMPOLABOR { get; set; }
        public virtual DbSet<STRUCTURES> STRUCTURES { get; set; }
        public virtual DbSet<SUM_PROJECT_ACTIVITY> SUM_PROJECT_ACTIVITY { get; set; }
        public virtual DbSet<SUM_TASK_NOT_LINKED_ASBPS> SUM_TASK_NOT_LINKED_ASBPS { get; set; }
        public virtual DbSet<SUM_ZNI_TASK_ASBPS> SUM_ZNI_TASK_ASBPS { get; set; }
        public virtual DbSet<ASBPS_ACT_SPEC_OCT> ASBPS_ACT_SPEC_OCT { get; set; }
        public virtual DbSet<NKFO2_ACT_SPEC_OCT> NKFO2_ACT_SPEC_OCT { get; set; }
        public virtual DbSet<SDBO_ACT_SPEC_OCT> SDBO_ACT_SPEC_OCT { get; set; }
    }
}
