//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NKFO2_ACT_SPEC_NOV
    {
        public string ПОДРАЗДНИЗ { get; set; }
        public string ПОДРАЗДВЕРХ { get; set; }
        public string КОДЗНИ { get; set; }
        public string НОМЕР_ЗНИ { get; set; }
        public Nullable<System.DateTime> ДАТА_РЕГ { get; set; }
        public string МЕНЕДЖЕР_ДИТ { get; set; }
        public string ИСТОЧНИК_ЗНИ { get; set; }
        public Nullable<System.DateTime> ДАТА_РЕГ_ЗНИ { get; set; }
        public string СТАТУСЗНИ { get; set; }
        public Nullable<System.DateTime> ДАТАРЕЗОЛЗНИ { get; set; }
        public string КОДЗАДАЧИ { get; set; }
        public string ОПИСАНИЕ_РАБОТЫ { get; set; }
        public string СТАТУСЗАДАЧИ { get; set; }
        public Nullable<System.DateTime> ДАТАРЕЗОЛЗАДАЧИ { get; set; }
        public Nullable<System.DateTime> ДАТАСОЗДЗАДАЧИ { get; set; }
        public System.DateTime ДАТА_РАБОТЫ { get; set; }
        public string АС_НОМЕР { get; set; }
        public string АС_НАЗВАНИЕ { get; set; }
        public Nullable<decimal> СУМТРУД { get; set; }
        public string ПОЛНОЕ_ИМЯ { get; set; }
        public Nullable<decimal> GRADE { get; set; }
        public decimal ТРУДОЗАТРАТЫ { get; set; }
        public string WORK_TYPE_VAL { get; set; }
    }
}
