//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRUCTURES
    {
        public Nullable<int> ID { get; set; }
        public Nullable<int> ID_STRUCT { get; set; }
        public string NAME_STRUCT { get; set; }
        public Nullable<int> ID_ROOT { get; set; }
        public string NAME_ROOT { get; set; }
        public Nullable<decimal> ID_CHILD { get; set; }
        public string NAME_CHILD { get; set; }
    }
}
