//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUM_TASK_NOT_LINKED_ASBPS
    {
        public decimal ID { get; set; }
        public string МЕСЯЦ { get; set; }
        public Nullable<decimal> ВРЕМЯ_Ч { get; set; }
    }
}
