//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPOLABOR
    {
        public int ID { get; set; }
        public int ID_TIMESHEET { get; set; }
        public int ID_ISSUE { get; set; }
        public string ISSUE_NAME { get; set; }
        public string SUMMARY { get; set; }
        public decimal TIMESPENT { get; set; }
        public System.DateTime WORKDATE { get; set; }
        public string FULL_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string ISSUE_TYPE { get; set; }
        public int ID_PROJECT { get; set; }
        public string DESCRIPTION { get; set; }
        public string WORK_TYPE_VAL { get; set; }
        public string AS_NUM { get; set; }
        public string AS_VAL { get; set; }
        public string ACCOUNT_VAL { get; set; }
    }
}
